component: nextjs@0.0.0-dev
name: nextjsApp
org: test
app: nextjsApp
stage: dev

inputs:
  src: ./src
  region: ap-guangzhou
  runtime: Nodejs10.15
  exclude:
    - .env
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
